apiVersion: tekton.dev/v1
kind: Pipeline
metadata:
  name: rteval-testing-farm-pipeline
spec:
  description: >-

    Pipeline to test the image using Testing Farm. It consists of three tasks

    1. Task "pre-process" creates the default value for 'PULL_SECRET_NAME'
    2. Task "scheduler" detects requests Testing farm to test just the modified component
       and is responsible to set all parameters requires to do so (pull secret value, image url...)
       Fills REQUEST_URL result with the link to the testing farm.
    3. Task "wait-for-results" waits until Testing farm finishes with the request and parses the output.
       Sets the final TEST_OUTPUT result as well as ARTIFACTS_URL to the overview of the test result.


    Secret to create:
      Key/value with key `testing-farm-token` containing the testing-farm API token.
      Provide name of this secret as `TESTING_FARM_TOKEN_SECRET_NAME` parameter.
      
    Required parameters:
      `SNAPSHOT` which is provided by the pipeline automatically

    Important parameters:
      `PULL_SECRET_NAME` name of the 'Image pull' secret (typekubernetes.io/dockerconfigjson).
        If not set the name  "imagerepository-for-${APPLICATION}-${COMPONENT}-image-pull" is used.

      TESTING_FARM_TOKEN_SECRET_NAME name of secret containing the testing-farm API token
        If not set the name "testing-farm-secret" is used.


  params:
    - name: SNAPSHOT
      description: A list of container images that should undergo testing
    - name: PULL_SECRET_NAME
      description: Explicit name of pull secret to use, detected by app/comp name otherwise
      default: ""
    - name: TESTING_FARM_TOKEN_SECRET_NAME
      default: "testing-farm-secret"
      description: Name of the Key/Value secret with testing-farm-token key
    - name: GIT_URL
      default: ""
      description: URL of the GIT repository that contains the tests.
    - name: TMT_PLAN
      default: "."
      description: Name filter for plans defined in the repo.
    - name: GIT_REF
      default: ""
      description: Branch of the git repository used containing the tests
    - name: COMPOSE
      default: "Fedora-40"
      description: Compose to use for the system-under-test.
    - name: ARCH
      default: "x86_64"
      description: Comma-separated list of architectures to run against.
    - name: TIMEOUT
      default: "720"
      description: Set the timeout for the request in minutes. If the test takes longer than this, it will be terminated.
    - name: TESTING_FARM_API_URL
      default: https://api.dev.testing-farm.io/v0.1
      description: The testing-farm instance API to use
  results:
    - name: REQUEST_URL
      value: "$(tasks.scheduler.results.tf-request)"
    - name: ARTIFACTS_URL
      value: "$(tasks.wait-for-results.results.ARTIFACTS_URL)"
    - name: TEST_OUTPUT
      value: "$(tasks.wait-for-results.results.TEST_OUTPUT)"
  tasks:
    - name: pre-process
      timeout: "5m"
      taskRef:
        resolver: git
        params:
          - name: url
            value: https://github.com/wchwhite/testing-farm-tekton
          - name: revision
            value: main
          - name: pathInRepo
            value: tasks/pre-process.yaml
      params:
        - name: SNAPSHOT
          value: $(params.SNAPSHOT)
    - name: scheduler
      runAfter:
        - pre-process
      timeout: "5m"
      taskRef:
        resolver: git
        params:
          - name: url
            value: https://github.com/wchwhite/testing-farm-tekton
          - name: revision
            value: main
          - name: pathInRepo
            value: tasks/scheduler.yaml
      params:
        - name: PULL_SECRET_NAME
          value: "$(tasks.pre-process.results.pull-secret-name)"
        - name: TESTING_FARM_TOKEN_SECRET_NAME
          value: "$(params.TESTING_FARM_TOKEN_SECRET_NAME)"
        - name: SNAPSHOT
          value: $(params.SNAPSHOT)
        - name: GIT_URL
          value: $(params.GIT_URL)
        - name: TMT_PLAN
          value: $(params.TMT_PLAN)
        - name: GIT_REF
          value: $(params.GIT_REF)
        - name: COMPOSE
          value: $(params.COMPOSE)
        - name: ARCH
          value: $(params.ARCH)
        - name: TIMEOUT
          value: $(params.TIMEOUT)
        - name: TESTING_FARM_API_URL
          value: $(params.TESTING_FARM_API_URL)
    - name: wait-for-results
      runAfter:
      - scheduler
      timeout: "5h"
      taskRef:
        resolver: git
        params:
          - name: url
            value: https://github.com/wchwhite/testing-farm-tekton
          - name: revision
            value: main
          - name: pathInRepo
            value: tasks/wait-for-results.yaml
      params:
        - name: TF_REQUEST
          value: "$(tasks.scheduler.results.tf-request)"